train_dataset_path: "dummy_objaverse\nsvd_meta.jsonl"
eval_dataset_path: "dummy_objaverse\nsvd_meta.jsonl"
batch_size: 2
dataset_type: "image_folder"
exp_name: "915test"
# report_to: "tensorboard"
report_to: "wandb"
learning_rate: 1e-5
weight_decay: 0
lr_scheduler: "constant"
warmup_steps: 0.05
eval_num_examples: 16
save_every_step: 1
eval_every_step: 1
gradient_checkpointing: True
gradient_accumulation_steps: 1
num_epoch: 1
num_frames: 7
eval_metric_names:
  - "psnr_score"
  - "clip_score"
  - "lpips_score"
num_inference_steps: 25
p_mean: 1.0
p_std: 1.6
condition_p_mean: -3
condition_p_std: 0.5